
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user_rate_question/new", "Create user_rate_question")) ?>
</div>

<?php echo $this->tag->form(array("user_rate_question/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user_rate_question</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="question_id">Question</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("question_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="qualification_id">Qualification</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("qualification_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="question_error_id">Question Of Error</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("question_error_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("updated_at", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
