
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user_answer/new", "Create user_answer")) ?>
</div>

<?php echo $this->tag->form(array("user_answer/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user_answer</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="answer_id">Answer</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("answer_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
