<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("question/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("question/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Question</th>
            <th>User</th>
            <th>Question Of Category</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Language</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $question) { ?>
        <tr>
            <td><?php echo $question->id ?></td>
            <td><?php echo $question->question ?></td>
            <td><?php echo $question->user_id ?></td>
            <td><?php echo $question->question_category_id ?></td>
            <td><?php echo $question->created_at ?></td>
            <td><?php echo $question->updated_at ?></td>
            <td><?php echo $question->language_id ?></td>
            <td><?php echo $this->tag->linkTo(array("question/edit/" . $question->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("question/delete/" . $question->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("question/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("question/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("question/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("question/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
