
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("answer/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("answer", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit answer</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="question_id">Question</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("question_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="answer">Answer</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("answer", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="correct">Correct</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("correct", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("updated_at", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
