
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("answer/new", "Create answer")) ?>
</div>

<?php echo $this->tag->form(array("answer/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search answer</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="question_id">Question</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("question_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="answer">Answer</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("answer", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="correct">Correct</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("correct", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("updated_at", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
