
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("friendship/new", "Create friendship")) ?>
</div>

<?php echo $this->tag->form(array("friendship/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search friendship</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="friend_id">Friend</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("friend_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
