<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("friendship/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("friendship/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Friend</th>
            <th>Created</th>
            <th>Type</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $friendship) { ?>
        <tr>
            <td><?php echo $friendship->id ?></td>
            <td><?php echo $friendship->user_id ?></td>
            <td><?php echo $friendship->friend_id ?></td>
            <td><?php echo $friendship->created_at ?></td>
            <td><?php echo $friendship->type ?></td>
            <td><?php echo $this->tag->linkTo(array("friendship/edit/" . $friendship->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("friendship/delete/" . $friendship->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("friendship/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("friendship/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("friendship/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("friendship/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
