
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user/new", "Create user")) ?>
</div>

<?php echo $this->tag->form(array("user/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastname">Lastname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_id">Facebook</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("facebook_id", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_token">Facebook Of Token</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_token", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="google_id">Google</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("google_id", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("updated_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="language_id">Language</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("language_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_session">Last Of Session</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("last_session", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
