<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("user/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("user/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Name</th>
            <th>Lastname</th>
            <th>Facebook</th>
            <th>Facebook Of Token</th>
            <th>Google</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Language</th>
            <th>Last Of Session</th>
            <th>Status</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user) { ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->lastname ?></td>
            <td><?php echo $user->facebook_id ?></td>
            <td><?php echo $user->facebook_token ?></td>
            <td><?php echo $user->google_id ?></td>
            <td><?php echo $user->created_at ?></td>
            <td><?php echo $user->updated_at ?></td>
            <td><?php echo $user->language_id ?></td>
            <td><?php echo $user->last_session ?></td>
            <td><?php echo $user->status ?></td>
            <td><?php echo $this->tag->linkTo(array("user/edit/" . $user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("user/delete/" . $user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("user/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
