
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("trophy_description/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("trophy_description", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit trophy_description</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="trophy_id">Trophy</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("trophy_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="language_id">Language</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("language_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
