
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("trophy_description/new", "Create trophy_description")) ?>
</div>

<?php echo $this->tag->form(array("trophy_description/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search trophy_description</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="trophy_id">Trophy</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("trophy_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="language_id">Language</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("language_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
