
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user_trophy/new", "Create user_trophy")) ?>
</div>

<?php echo $this->tag->form(array("user_trophy/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user_trophy</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="trophy_id">Trophy</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("trophy_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("created_at", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("updated_at", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
