<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("user_trophy/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("user_trophy/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>User</th>
            <th>Trophy</th>
            <th>Created</th>
            <th>Updated</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user_trophy) { ?>
        <tr>
            <td><?php echo $user_trophy->id ?></td>
            <td><?php echo $user_trophy->user_id ?></td>
            <td><?php echo $user_trophy->trophy_id ?></td>
            <td><?php echo $user_trophy->created_at ?></td>
            <td><?php echo $user_trophy->updated_at ?></td>
            <td><?php echo $this->tag->linkTo(array("user_trophy/edit/" . $user_trophy->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("user_trophy/delete/" . $user_trophy->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("user_trophy/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("user_trophy/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("user_trophy/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("user_trophy/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
