
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("question_error/new", "Create question_error")) ?>
</div>

<?php echo $this->tag->form(array("question_error/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search question_error</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
